name: Create Release

on:
  push:
    tags:
      - 'v*'  # Triggers on version tags like v1.2.3

jobs:
  build-and-release:
    runs-on: windows-latest
    
    steps:

    # Ensure the version tag is formatted like "v1.2.3".
    - name: Validate version tag
      run: |
        if ("${{ github.ref_name }}" -notmatch '^v\d+\.\d+\.\d+') {
          Write-Error "Invalid version tag format"
          exit 1
        }
    
    - name: Checkout code
      uses: actions/checkout@v4
      with:
        fetch-depth: 0  # Fetch all history to check branch ancestry, needed for branch validation.

    - name: Verify tag is on main branch
      run: |
        $branches = git branch -r --contains ${{ github.sha }}
        if ($branches -notmatch 'origin/main') {
          Write-Error "Tag must point to a commit on the main branch"
          exit 1
        }
    
    - name: Setup .NET
      uses: actions/setup-dotnet@v4
      with:
        dotnet-version: '8.0.x'
    
    - name: Restore dependencies
      run: dotnet restore
    
    - name: Build
      run: dotnet build WinApp/WinApp.csproj --configuration Release --no-restore
    
    - name: Publish
      run: dotnet publish WinApp/WinApp.csproj --configuration Release --runtime win-x86 --self-contained false -p:PublishSingleFile=true -p:DebugType=None -p:DebugSymbols=false --output ./publish --no-build
    
    - name: Zip Release
      run: |
        $version = "${{ github.ref_name }}" -replace '^v', ''
        Compress-Archive -Path ./publish/* -DestinationPath ./J-Rdp_${version}_win-x86.zip
    
    - name: Read release notes template
      id: release_notes
      run: |
        $content = Get-Content -Path ./.dev/ReleaseTemplate.md -Raw
        "release_notes_template<<EOF" >> $env:GITHUB_OUTPUT
        $content >> $env:GITHUB_OUTPUT
        "EOF" >> $env:GITHUB_OUTPUT
    
    - name: Create Release
      uses: softprops/action-gh-release@v1
      with:
        files: ./J-Rdp_*_win-x86.zip
        body: ${{ steps.release_notes.outputs.release_notes_template }}
        draft: true
        prerelease: true
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}